
spring:
  datasource:
        url: jdbc:postgresql://dpg-crc3lb3v2p9s73dlticg-a.oregon-postgres.render.com:5432/solidid_b93u
        username: solidid
        password: Ta9UiZGfOBpmipavYH1uvHSmJcWpWwhw
        driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

