
#spring:
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/solidID"
#    username: postgres
#    password: 211999
#    driverClassName: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#spring:
#  datasource:
#    url: "jdbc:postgresql://postgres.chsswwcsu6lg.us-east-1.rds.amazonaws.com:5432/postgres"
#    username: postgres
#    password: postgres
#    driverClassName: org.postgresql.Driver
#    jpa:
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#      hibernate:
#        ddl-auto: update
#      show-sql: true

spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driverClassName: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true






